# Generated by Django 4.2.13 on 2024-06-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0002_alter_pet_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
